trigger:
  branches:
    include:
      - main  # Trigger build on push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: InstallDependencies@0
  inputs:
    packageManager: 'pip'
    workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/app
    ArtifactName: drop
    publishLocation: Container
